semi: true
singleQuote: true
bracketSpacing: false
overrides:
  - files:
      - "*.yml"
      - "*.yaml"
      - "*.css"
      - "*.html"
    options:
      singleQuote: false
plugins:
  - prettier-plugin-tailwindcss
