name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "Environment to deploy to"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "environment: ${{ inputs.environment || 'production' }};"

  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - name: Checkout to "${{ github.ref }}".
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
        env:
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}
      - uses: actions/upload-pages-artifact@v2
        with:
          name: bundle
          path: out
