name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to deploy to"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout to "${{ github.ref }}".
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
        env:
          BUILD: ${{ github.sha }}
          ENVIRONMENT: ${{ inputs.environment }}
          FARO_COLLECTOR_URL: ${{ vars.FARO_COLLECTOR_URL }}
          GISCUS_CATEGORY_ID: ${{ vars.GISCUS_CATEGORY_ID }}
          GISCUS_CATEGORY: ${{ vars.GISCUS_CATEGORY }}
          GISCUS_REPO_ID: ${{ vars.REPO_ID }}
          GISCUS_REPO: ${{ github.repository }}
          GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}
          ORIGIN: ${{ vars.WEBSITE_ORIGIN }}
      - uses: actions/upload-pages-artifact@v3
        with:
          name: bundle
          path: dist
