name: Publish Debug

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - production
          - staging
        required: true
        description: 'Environment to deploy to'
  push:
    branches:
      - debug

env:
  environment: ${{ inputs.environment || 'production' }}

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}
    steps:
      - run: |
          echo "env.environment: ${{ env.environment }};"
          echo "inputs.environment: ${{ inputs.environment }};"
