name: Publish

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - production
          - staging
        required: true
        description: "Environment to deploy to"
  push:
    branches:
      - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

env:
  environment: ${{ inputs.environment || 'production' }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment || 'production' }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: bundle
